FROM oai_base

WORKDIR /root/son-epc/scripts
RUN git pull
RUN python3 setup.py install

COPY spgw.conf /root/son-epc/scripts/server.conf
COPY spgw.sh /root/son-epc/scripts/start.sh

RUN cp /root/openair-cn/ETC/spgw.conf /usr/local/etc/oai
RUN cp /root/openair-cn/ETC/acl.conf /usr/local/etc/oai/freeDiameter
RUN sed -i -r 's/(TRAFFIC_SHAPPING_ENABLED\s*=\s*")yes(";.*$)/\1no\2/' /usr/local/etc/oai/spgw.conf

ENV SON_EMU_CMD "/root/son-epc/scripts/start.sh"

CMD /bin/bash
