FROM oai_base

WORKDIR /root/son-epc/scripts
RUN git pull
RUN python3 setup.py install

COPY mme.conf /root/son-epc/scripts/server.conf
COPY mme.sh /root/son-epc/scripts/start.sh

RUN cp /root/openair-cn/ETC/mme.conf /usr/local/etc/oai
RUN cp /root/openair-cn/ETC/mme_fd.conf /usr/local/etc/oai/freeDiameter
RUN cp /root/openair-cn/ETC/acl.conf /usr/local/etc/oai/freeDiameter

ENV SON_EMU_CMD "/root/son-epc/scripts/start.sh"

CMD /bin/bash

