FROM oai_base

WORKDIR /root/son-epc/scripts
RUN git pull
RUN python3 setup.py install

COPY hss.conf /root/son-epc/scripts/server.conf
COPY hss.sh /root/son-epc/scripts/start.sh

RUN cp /root/openair-cn/ETC/hss.conf /usr/local/etc/oai
RUN cp /root/openair-cn/ETC/hss_fd.conf /usr/local/etc/oai/freeDiameter
RUN cp /root/openair-cn/ETC/acl.conf /usr/local/etc/oai/freeDiameter

ENV SON_EMU_CMD "son-vm-server -v -c /root/son-epc/oai/hss.conf"

CMD son-vm-server -v -c /root/son-epc/oai/hss.conf

