FROM oai_base

WORKDIR /root/son-epc/scripts
RUN git pull
RUN python3 setup.py install

COPY hss.conf /root/son-epc/scripts/server.conf
COPY hss.sh /root/son-epc/scripts/start.sh

ENV SON_EMU_CMD "/root/son-epc/scripts/start.sh"

CMD /bin/bash

