version: '3'

services:
  epc_deps:
    build:
      context: .
      dockerfile: Dockerfile.deps
    image: epc_deps:SNAPSHOT

  epc_base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: epc_base:SNAPSHOT
    depends_on:
      - epc_deps

  mme_pp:
    build:
      context: .
      dockerfile: Dockerfile.mme
    image: mme_pp:SNAPSHOT
    container_name: mme_pp
    depends_on:
      - epc_base

  hss_pp:
    build:
      context: .
      dockerfile: Dockerfile.hss
    image: hss_pp:SNAPSHOT
    container_name: hss_pp
    depends_on:
      - epc_base

  pgw_pp:
    build:
      context: .
      dockerfile: Dockerfile.pgw
    image: pgw_pp:SNAPSHOT
    container_name: pgw_pp
    depends_on:
      - epc_base

  sgw_pp_1:
    build:
      context: .
      dockerfile: Dockerfile.sgw
    image: sgw_pp:SNAPSHOT
    container_name: sgw_pp_1
    depends_on:
      - epc_base
    privileged: true

  sgw_pp_2:
    build:
      context: .
      dockerfile: Dockerfile.sgw
    image: sgw_pp:SNAPSHOT
    container_name: sgw_pp_2
    depends_on:
      - epc_base
    privileged: true

  lb_pp:
    build:
      context: .
      dockerfile: Dockerfile.lb
    image: lb_pp:SNAPSHOT
    container_name: lb_pp
    depends_on:
      - epc_base
    privileged: true
